---

- name: Rabbitmq setup (install + optional keycloak)
  ansible.builtin.include_tasks:
    file: "{{ item }}"
    apply:
      tags:
        - install
  loop: "{{ rabbitmq_task_files }}"
  tags:
    - install

- name: Uninstall -> RabbitMQ using Helm
  ansible.builtin.include_tasks:
    file: uninstall_rabbitmq.yml
    apply:
      tags:
        - uninstall
  tags:
    - uninstall
