---

- name: Uninstall release '{{ rabbitmq_release_name }}' in namespace '{{ rabbitmq_namespace }}'
  ansible.builtin.command:
    cmd: helm uninstall {{ rabbitmq_release_name }} -n {{ rabbitmq_namespace }}
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"

- name: Remove rabbitmq values directory
  ansible.builtin.file:
    path: "{{ rabbitmq_values_file }}"
    state: absent

- name: Uninstall release '{{ rabbitmq_ingress_release_name }}' in namespace '{{ rabbitmq_namespace }}'
  ansible.builtin.command:
    cmd: helm uninstall {{ rabbitmq_ingress_release_name }} -n {{ rabbitmq_namespace }}
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"

- name: Remove rabbitmq ingress helm directory
  become: true
  ansible.builtin.file:
    path: "{{ rabbitmq_config_dir }}/helm_chart"
    state: absent


