---
- name: Setup Digital Twin Frontend
  hosts: master
  roles:
    - kubernetes
    - helm
  vars:
    helm_state: present
    helm_version: "v3.12.3"
  tags: kubernetes

- name: Setup Digital Twin Backend
  hosts: backend
  become: true
  roles:
    - kubernetes
  tags: kubernetes

# file: site.yml
- name: Setup Digital Twin Backend
  import_playbook: backend.yml
  tags: docker

- name: Setup Digital Twin Frontend
  import_playbook: frontend.yml
  tags: docker

- name: Setup Terraform on Mac
  hosts: master
  roles:
    - terraform
