---

- name: Deploy Backend services using Kubernetes
  kubernetes.core.k8s:
    kubeconfig: "{{ lookup('env','HOME') + '/.kube/config' }}"
    state: present
    src: "{{ item }}"
    namespace: "{{ backend_k8s_namespace }}"
  loop: "{{ lookup('fileglob', backend_k8s_service_path + '/*.yml', wantlist=True) }}"    
  register: backend_apply

- name: Show result
  ansible.builtin.debug:
    var: backend_apply
