---

- name: Install -> Backend Services
  ansible.builtin.include_tasks:
    file: build_images.yml
    apply:
      tags:
        - install
  tags:
    - install

- name: Uninstall -> Backend Services
  ansible.builtin.include_tasks:
    file: remove_images.yml
    apply:
      tags:
        - uninstall
  tags:
    - uninstall
