---

- name: Disable backend service
  ansible.builtin.systemd:
    name: digital-twin-backend
    enabled: false
    state: stopped
  ignore_errors: true

- name: Reset systemd daemon
  ansible.builtin.systemd:
    daemon_reload: false
  ignore_errors: true

- name: Remove systemd service file for digital-twin-backend
  ansible.builtin.file:
    path: /etc/systemd/system/digital-twin-backend.service
    state: absent

- name: Stop Backend docker containers and removes it
  ansible.builtin.shell:
    cmd: cd "{{ backend_service_path }}" && docker compose down --remove-orphans
  become: true
  become_user: "{{ ansible_user }}"
  ignore_errors: true
