---

- name: Remove Backend repository
  ansible.builtin.file:
    path: "{{ backend_service_path }}"
    state: absent

- name: Remove backend repository
  ansible.builtin.file: 
    path: "{{ backend_k8s_service_path }}"
    state: absent