---

- name: Uninstall Backend - Services
  kubernetes.core.k8s:
    kubeconfig: "{{ lookup('env','HOME') + '/.kube/config' }}"
    state: absent
    src: "{{ backend_k8s_service_path }}/03-service.yml"
    namespace: "{{ backend_k8s_namespace }}"

- name: Uninstall Backend - Deployments
  kubernetes.core.k8s:
    kubeconfig: "{{ lookup('env','HOME') + '/.kube/config' }}"
    state: absent
    src: "{{ backend_k8s_service_path }}/02-deployment.yml"
    namespace: "{{ backend_k8s_namespace }}"

- name: Uninstall Backend - PVCs
  kubernetes.core.k8s:
    kubeconfig: "{{ lookup('env','HOME') + '/.kube/config' }}"
    state: absent
    src: "{{ backend_k8s_service_path }}/01-pvc.yml"
    namespace: "{{ backend_k8s_namespace }}"