---

- name: Build frontend imags and push to docker registry
  ansible.builtin.command:
    cmd: docker buildx build 
        --platform linux/amd64,linux/arm64 
        -t "{{ docker_registry }}/frontend_digital_twin_app:latest" 
        --cache-from=type=registry,ref={{ docker_registry }}/frontend_digital_twin_app:latest 
        --push .
  args:
    chdir: "{{ playbook_dir }}/../../apps/frontend/app"
  register: built_result
  environment:
    DOCKER_BUILDKIT: "1"
  delegate_to: localhost
