---

- name: Uninstall frontend using Kubernetes - Services
  kubernetes.core.k8s:
    kubeconfig: "{{ lookup('env','HOME') + '/.kube/config' }}"
    state: absent
    src: "{{ frontend_k8s_service_path }}/03-service.yml"
    namespace: "{{ frontend_k8s_namespace }}"

- name: Uninstall frontend using Kubernetes - Deployments
  kubernetes.core.k8s:
    kubeconfig: "{{ lookup('env','HOME') + '/.kube/config' }}"
    state: absent
    src: "{{ frontend_k8s_service_path }}/02-deployment.yml"
    namespace: "{{ frontend_k8s_namespace }}"

- name: Uninstall frontend using Kubernetes - PVCs
  kubernetes.core.k8s:
    kubeconfig: "{{ lookup('env','HOME') + '/.kube/config' }}"
    state: absent
    src: "{{ frontend_k8s_service_path }}/01-pvc.yml"
    namespace: "{{ frontend_k8s_namespace }}"

