---

- name: Disable digital-twin-frontend service
  ansible.builtin.systemd:
    name: digital-twin-frontend
    enabled: false
    state: stopped
  ignore_errors: true
  when: ansible_facts['os_family'] != "Darwin"

- name: Reset systemd daemon
  ansible.builtin.systemd:
    daemon_reload: false
  ignore_errors: true
  when: ansible_facts['os_family'] != "Darwin"

- name: Remove systemd service file for ddigital-twin-frontend
  ansible.builtin.file:
    path: /etc/systemd/system/digital-twin-frontend.service
    state: absent
  when: ansible_facts['os_family'] != "Darwin"

- name: Unload launchd service
  command: launchctl unload /Library/LaunchDaemons/com.digital-twin-frontend.docker.plist
  become: true
  when: ansible_facts['os_family'] == "Darwin"

- name: Remove launchd service file for digital-twin-frontend
  ansible.builtin.file:
    path: /Library/LaunchDaemons/com.digital-twin-frontend.docker.plist
    state: absent
  become: true
  when: ansible_facts['os_family'] == "Darwin"  

- name: Stop Docker containers and removes it
  ansible.builtin.shell:
    cmd: cd "{{ frontend_service_path }}" && docker compose down --remove-orphans
  ignore_errors: true

