[tool.poetry]
name = "edge_server"
version = "0.1.0"
description = ""
authors = ["Suhas Pachling <suhas@test.com>"]
readme = "README.md"
packages = [
    { include = "src" }
]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.32.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
