---

# - name: Setup kubernetes, helm, grafana and prometheus on mac
#   hosts: mac
#   vars_files:
#     - ../group_vars/mac.vault.yml  # relative to playbook
#   roles:
#     - kubernetes

- name: Setup Terraform, aws sdk and grafana on Mac
  hosts: mac
  become: true
  roles:
    - terraform
    - grafana_docker
    - aws_sdk
