[tool.poetry]
name = "edge-server"
version = "0.2.1"
description = ""
authors = ["Suhas Pachling <suhas@test.com>"]
readme = "README.md"
packages = [
    { include = "edge_server", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
requests = "^2.32.5"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
black = "^23.10.0"
flake8 = "^6.1.0"
pre-commit = "^4.0.0"


[tool.poetry.group.security.dependencies]
semgrep = "^1.163.0"
pip-audit = "^2.10.0"
poetry-plugin-export = "^1.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
addopts = "-v"
