name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

  workflow_dispatch:

jobs:

  ########################################################
  # Build and push python packages and docker images to Nexus
  ########################################################
  build-push:
    name: Build and push ${{ matrix.service_path }}
    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'
    runs-on: [self-hosted, debian, x64]

    strategy:
      fail-fast: false
      matrix:
        include:
          - service_path: apps/backend

          - service_path: apps/frontend

    steps:
      - uses: actions/checkout@v4

      # - name: Setup Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.14"

      - name: Check Python
        run: |
          python3 --version
          which python3

      - name: Install Poetry
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install poetry

      - name: Install Trivy
        env:
          TRIVY_VERSION: "0.64.1"
          TRIVY_TAG: "v0.64.1"
        run: |
          sudo apt-get update
          sudo apt-get install -y wget ca-certificates

          TRIVY_DEB="trivy_${TRIVY_VERSION}_Linux-64bit.deb"
          TRIVY_URL="https://github.com/aquasecurity/trivy/releases/download/${TRIVY_TAG}/${TRIVY_DEB}"
          TRIVY_SHA_URL="${TRIVY_URL}.sha256"

          wget -q "$TRIVY_URL" -O "/tmp/${TRIVY_DEB}"
          wget -q "$TRIVY_SHA_URL" -O "/tmp/${TRIVY_DEB}.sha256"
          sha256sum -c "/tmp/${TRIVY_DEB}.sha256"
          sudo dpkg -i "/tmp/${TRIVY_DEB}"
                    
      - name: Build, run docker scan and push image to Nexus
        working-directory: ${{ matrix.service_path }}
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_CA_CERT: ""
        run: |
          chmod +x build/build_and_push_nexus.sh
          ./build/build_and_push_nexus.sh

      - name: Cleanup Docker cache
        if: always()
        run: |
          docker system prune -af || true

  ########################################################
  # Deploy to k3s using Ansible
  ########################################################
  deploy:
    runs-on: [self-hosted, debian, x64]
    needs: build-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible collections
        run: |
          ansible-galaxy collection install kubernetes.core
          
      - name: Deploy microservices
        working-directory: setup/app/ansible
        run: |
          ansible-playbook \
            playbooks/apps.yml \
            -i hosts \
            -t install